ignored = ["github.com/onsi/ginkgo", "github.com/onsi/gomega"]

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "~1.30.0"

[[constraint]]
  name = "github.com/goshield/interfaces"
  version = "1.2.x"

[prune]
  go-tests = true
  unused-packages = true
